# Generated by Django 3.1.6 on 2021-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210205_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='auuthor_pictures'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
