# Generated by Django 3.1.6 on 2021-02-07 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0011_auto_20210207_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='book',
            name='posted_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
    ]
